/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include<stdint.h>
#include<stdlib.h>
#include<stdio.h>
#include"Platform_Types.h"

#define RCC_BASE     0x40021000
#define GPIOA_BASE   0x40010800
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE+0x18)
#define GPIOA_CRH    *(volatile uint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_ODR    *(volatile uint32_t *)(GPIOA_BASE+0x0c)

#define RCC_IOPAEN   (1<<2)
#define GPIOA13      (1UL<<13)



typedef union {
	vuint32_t allfields;
	struct{
		vuint32_t reserved:13;
		vuint32_t p_13:1;
	}pin;

}R_ODR_t;

volatile R_ODR_t * R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0c);
unsigned char g_variales[3]={1,2,3};
unsigned char const const_variables[3]={1,2,3};
volatile unsigned char bss_var[3];

void* _sbrk(int incr)
{
	static unsigned char* heap_ptr=NULL;
	unsigned char* prev_heap_ptr=NULL;
	extern unsigned int _E_bss;
	extern unsigned int _heap_End;
	//First time intialized
	if(heap_ptr==NULL)
		heap_ptr=(unsigned char *)&_E_bss;
	
	
	prev_heap_ptr=heap_ptr;
	
	//protect stack
	if((heap_ptr+incr)>((unsigned char *)&_heap_End))
		return (void*) NULL;
	
	heap_ptr+=incr;
	return (void*)prev_heap_ptr;
}

int main(void){
	int *p=(int *)malloc(4);
	free(p);
	RCC_APB2ENR |=RCC_IOPAEN;
	GPIOA_CRH   &=0xFF0FFFFF;
	GPIOA_CRH   |=0x00200000;
	while(1)
	{
		int i;
		R_ODR->pin.p_13=1;
		for(i=0;i<5000;i++);
		R_ODR->pin.p_13=0;
		for(i=0;i<5000;i++);
	}
	return 0;

}
