/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Keypad.h"
#include "lcd.h"
#include "Stm32_F103C6_EXTI_driver.h"

uint8_t IRQ_Flag ;


void clock_init()
{
	//Init clock for GPIOA
	RCC_GPIOA_CLK_EN();

	//Init clock for GPIOB
	RCC_GPIOB_CLK_EN() ;

	//Init clock for AFIO
	AFIO_GPIO_CLK_EN();
}


void delay(int x)
{
	unsigned i,j ;
	for(i=0; i<x; i++)
		for(j=0; j<255; j++);
}


void EXTI9_Callback(void)
{
	LCD_clear_screen();
	IRQ_Flag = 1 ;
	LCD_WRITE_STRING("IRQ EXTI9 is Happened _|--");
	delay(1000);

}


int main(void)
{

	clock_init();
	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXIT_PIN = EXTI9PB9 ;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_ENABLE	;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback ;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1 ;

	while(1)
	{
		if(IRQ_Flag)
		{
		LCD_clear_screen();
		IRQ_Flag = 0 ;
		}
	}

}
